import type { AnalysisResult, AssessmentQuality, Level } from "@/types/analysis";
const value = (number: number | null, suffix = "") => number === null ? "—" : `${number}${suffix}`;
function Card({ title, children, className = "" }: { title: string; children: React.ReactNode; className?: string }) { return <article className={`card ${className}`}><span className="card-title">{title}</span>{children}</article>; }
function Assessment({ label, item }: { label: string; item: { quality: AssessmentQuality; explanation: string } }) { return <Card title={label}><strong className={`quality ${item.quality.toLowerCase()}`}>{item.quality}</strong><p>{item.explanation}</p></Card>; }
function Levels({ title, levels }: { title: string; levels: Level[] }) { return <Card title={title}><div className="level-list">{levels.length ? levels.map((level, i) => <div key={`${level.price}-${i}`}><strong>{value(level.price)}</strong><span>{level.importance} · {level.reason}</span></div>) : <p>No reliable levels visible.</p>}</div></Card>; }
export function AnalysisDashboard({ result, image }: { result: AnalysisResult; image: string }) { const { probabilities: p } = result; const invalidation = result.direction === "SHORT" ? result.bullish_scenario.invalidation : result.bearish_scenario.invalidation;
  return <section className="dashboard" id="result">
    <div className="result-head"><div><div className="section-kicker">Analysis complete</div><h2>{result.asset || "Chart setup"}</h2><p className="muted">{result.timeframe || "Timeframe not visible"} · interpretation based on screenshot evidence</p></div><div className={`direction ${result.direction.toLowerCase()}`}>{result.direction}</div></div>
    <div className="command-grid"><div className="chart-card"><img src={image} alt="Chart analyzed by BullGPT"/><p>Annotations are shown as structured results rather than inaccurate chart overlays.</p></div><div className="decision-panel"><div className="overall"><span className="card-title">Overall assessment</span><strong>{result.setup.quality}</strong><p>{result.overall_assessment}</p></div><div className="probability prominent"><div className="prob-label"><b className="bull">BULLISH <em>{p.bullish}%</em></b><b className="bear">BEARISH <em>{p.bearish}%</em></b></div><div className="bar"><i style={{ width: `${p.bullish}%` }}/></div><small>Relative scenario estimates — not certainty.</small></div><div className="key-metrics"><div><span>Setup score</span><b>{value(result.setup.score)}</b></div><div><span>Confidence</span><b>{result.confidence}%</b></div><div><span>Risk / reward</span><b>{value(result.risk_reward, "R")}</b></div></div></div></div>
    <div className="trade-levels"><Card title="Entry"><strong>{value(result.entry)}</strong><p>{result.entry_assessment.explanation}</p></Card><Card title="Stop loss"><strong className="bear">{value(result.stop_loss)}</strong><p>{result.stop_loss_assessment.explanation}</p></Card><Card title="Take profit"><strong className="bull">{value(result.take_profit)}</strong><p>{result.take_profit_assessment.explanation}</p></Card><Card title="Invalidation" className="invalidation"><strong>{invalidation}</strong><p>A setup is conditional. Reassess if this condition occurs.</p></Card></div>
    <div className="cards three"><Card title="Market structure"><strong>{result.market_structure.classification}</strong><p>{result.market_structure.explanation}</p></Card><Card title="Trend"><strong>{result.trend.classification}</strong><p>{result.trend.explanation}</p></Card><Card title="Confluence"><strong>{value(result.confluence.score, "/100")}</strong><ul>{result.confluence.factors.length ? result.confluence.factors.map(x => <li key={x}>{x}</li>) : <li>No confluence could be reliably determined.</li>}</ul></Card></div>
    <div className="cards two"><Levels title="Support" levels={result.support_levels}/><Levels title="Resistance" levels={result.resistance_levels}/></div>
    <div className="cards two scenarios"><Card title="Bullish scenario" className="scenario bullish-scenario"><strong className="bull">{result.bullish_scenario.probability}% relative likelihood</strong><p>{result.bullish_scenario.description}</p><small><b>Confirmation</b>{result.bullish_scenario.confirmation}</small><small><b>Target</b>{result.bullish_scenario.target || "Not reliably visible"}</small></Card><Card title="Bearish scenario" className="scenario bearish-scenario"><strong className="bear">{result.bearish_scenario.probability}% relative likelihood</strong><p>{result.bearish_scenario.description}</p><small><b>Confirmation</b>{result.bearish_scenario.confirmation}</small><small><b>Target</b>{result.bearish_scenario.target || "Not reliably visible"}</small></Card></div>
    <div className="cards two"><Card title="Risk flags" className="risk-card"><ul className="risk-list">{result.risk_flags.length ? result.risk_flags.map(x => <li key={x}>{x}</li>) : <li>No material risk flag could be reliably determined.</li>}</ul></Card><Card title="Limits of this reading"><ul>{result.limitations.map(x => <li key={x}>{x}</li>)}</ul></Card></div>
  </section>; }
